### ISSUE TITLE
data download failed

### ISSUE THREAD

**Issue by HbueSky** [escuccim/mammography-models#1]
Hi, escuccim:
     I am very interested in your project and would like to try it. But, i encountered difficulties in downloading data, So, if possible, could you upload the data to a cloud disk, such as baidu cloud disk or google cloud disk?
    Thanks a lot!

**Comment by escuccim** [comment]
Dataset 1 was deleted from S3, that was the first dataset I created and it wasn't that great. I've had the best luck with datasets 6 and 8, download those by setting dataset = 6 or 8. 

Datasets 5, 6, 8 and 9 are still on S3. If you can't download those I can try to upload them elsewhere.

**Comment by HbueSky** [comment]
Many thanks! I'll follow.

**Comment by HbueSky** [comment]
I have downloaded all the dataset except dataset 1. Thanks again.

**Comment by escuccim** [comment]
I am happy to help.
